# Generated by Django 2.1.3 on 2018-11-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrades',
            name='school_subject',
        ),
        migrations.RemoveField(
            model_name='studentgrades',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grades',
        ),
        migrations.DeleteModel(
            name='SchoolSubject',
        ),
        migrations.DeleteModel(
            name='StudentGrades',
        ),
    ]
